[klientKonfigurasjon]
gruppeId = "migrering_v1"
eventlogTopic = "arbeidssoker-hendelseslogg-beta-v1"
periodeTopic = "arbeidssokerperioder-overforing-beta-v1"
situasjonTopic = "arbeidssoker-besvarelse-v2"

[serverKonfigurasjon]
autentisering = "PLAIN"
kafkaBrokers = "localhost:9092"
kafkaSchemaRegistry = "http://localhost:8082"

[schemaRegistryKonfigurasjon]
url = "http://localhost:8082"
