[klientKonfigurasjon]
gruppeId = "migrering_v2"
eventlogTopic = "arbeidssoker-hendelseslogg-beta-v2"
periodeTopic = "arbeidssokerperioder-overforing-beta-v1"
situasjonTopic = "arbeidssoker-besvarelse-v2"
opplysningerFraVeilarbTopic = "veilarb-opplysninger-mottatt-v1"

[serverKonfigurasjon]
autentisering = "PLAIN"
kafkaBrokers = "localhost:9092"
kafkaSchemaRegistry = "http://localhost:8082"

[schemaRegistryKonfigurasjon]
url = "http://localhost:8082"
