[klientKonfigurasjon]
konsumerGruppeId = "paw.arbsok_migrering_v5"
eventlogTopic = "paw.arbeidssoker-hendelseslogg-beta-v4"
periodeTopic = "paw.arbeidssokerperioder-overforing-beta-v1"
situasjonTopic = "paw.arbeidssoker-besvarelse-v2"
opplysningerFraVeilarbTopic = "paw.veilarb-opplysninger-mottatt-v1"

[serverKonfigurasjon]
autentisering = "SSL"
kafkaBrokers = "${KAFKA_BROKERS}"
kafkaSchemaRegistry = "${KAFKA_SCHEMA_REGISTRY}"
keystorePath = "${KAFKA_KEYSTORE_PATH}"
credstorePassword = "${KAFKA_CREDSTORE_PASSWORD}"
truststorePath = "${KAFKA_TRUSTSTORE_PATH}"

[schemaRegistryKonfigurasjon]
url = "${KAFKA_SCHEMA_REGISTRY}"
bruker = "${KAFKA_SCHEMA_REGISTRY_USER}"
passord = "${KAFKA_SCHEMA_REGISTRY_PASSWORD}"
