host = "${NAIS_DATABASE_PAW_MIGRERING_VEILARB_TIL_NYTT_REGISTER_ARBEIDSSOEKERMIGRERING_HOST}"
port = "${NAIS_DATABASE_PAW_MIGRERING_VEILARB_TIL_NYTT_REGISTER_ARBEIDSSOEKERMIGRERING_PORT}"
brukernavn = "${NAIS_DATABASE_PAW_MIGRERING_VEILARB_TIL_NYTT_REGISTER_ARBEIDSSOEKERMIGRERING_USERNAME}"
passord = "${NAIS_DATABASE_PAW_MIGRERING_VEILARB_TIL_NYTT_REGISTER_ARBEIDSSOEKERMIGRERING_PASSWORD}"
databasenavn = "${NAIS_DATABASE_PAW_MIGRERING_VEILARB_TIL_NYTT_REGISTER_ARBEIDSSOEKERMIGRERING_DATABASE}"